[build-system]
requires = [
    "setuptools>=42",
    "setuptools_scm",
    "wheel",
    "pybind11==2.9.2",
]

build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = [ "pytest" ]
