# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dragonradio.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dragonradio.proto',
  package='dragonradio.remote',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x64ragonradio.proto\x12\x12\x64ragonradio.remote\"c\n\x04Goal\x12\x11\n\tgoal_type\x18\x01 \x01(\t\x12\x10\n\x08\x66low_uid\x18\x02 \x01(\x05\x12\x36\n\x0crequirements\x18\x03 \x01(\x0b\x32 .dragonradio.remote.Requirements\"\x9a\x01\n\x0cRequirements\x12\x15\n\rmax_latency_s\x18\x01 \x01(\x02\x12\x1a\n\x12min_throughput_bps\x18\x02 \x01(\x02\x12\x1c\n\x14max_packet_drop_rate\x18\x03 \x01(\x02\x12 \n\x18\x66ile_transfer_deadline_s\x18\x04 \x01(\x02\x12\x17\n\x0f\x66ile_size_bytes\x18\x05 \x01(\x02\"@\n\x06Status\x12(\n\x05state\x18\x01 \x01(\x0e\x32\x19.dragonradio.remote.State\x12\x0c\n\x04info\x18\x02 \x01(\t\";\n\x10MandatedOutcomes\x12\'\n\x05goals\x18\x01 \x03(\x0b\x32\x18.dragonradio.remote.Goal\"\x90\x01\n\x07Request\x12\x39\n\rradio_command\x18\x01 \x01(\x0e\x32 .dragonradio.remote.RadioCommandH\x00\x12?\n\x0fupdate_outcomes\x18\x02 \x01(\x0b\x32$.dragonradio.remote.MandatedOutcomesH\x00\x42\t\n\x07payload\"C\n\x08Response\x12,\n\x06status\x18\x01 \x01(\x0b\x32\x1a.dragonradio.remote.StatusH\x00\x42\t\n\x07payload*[\n\x05State\x12\x07\n\x03OFF\x10\x00\x12\x0b\n\x07\x42OOTING\x10\x01\x12\t\n\x05READY\x10\x02\x12\n\n\x06\x41\x43TIVE\x10\x03\x12\x0c\n\x08STOPPING\x10\x04\x12\x0c\n\x08\x46INISHED\x10\x05\x12\t\n\x05\x45RROR\x10\x06*/\n\x0cRadioCommand\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01\x12\n\n\x06STATUS\x10\x02\x62\x06proto3')
)

_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='dragonradio.remote.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFF', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOOTING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='READY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOPPING', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINISHED', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=642,
  serialized_end=733,
)
_sym_db.RegisterEnumDescriptor(_STATE)

State = enum_type_wrapper.EnumTypeWrapper(_STATE)
_RADIOCOMMAND = _descriptor.EnumDescriptor(
  name='RadioCommand',
  full_name='dragonradio.remote.RadioCommand',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=735,
  serialized_end=782,
)
_sym_db.RegisterEnumDescriptor(_RADIOCOMMAND)

RadioCommand = enum_type_wrapper.EnumTypeWrapper(_RADIOCOMMAND)
OFF = 0
BOOTING = 1
READY = 2
ACTIVE = 3
STOPPING = 4
FINISHED = 5
ERROR = 6
START = 0
STOP = 1
STATUS = 2



_GOAL = _descriptor.Descriptor(
  name='Goal',
  full_name='dragonradio.remote.Goal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='goal_type', full_name='dragonradio.remote.Goal.goal_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flow_uid', full_name='dragonradio.remote.Goal.flow_uid', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requirements', full_name='dragonradio.remote.Goal.requirements', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=140,
)


_REQUIREMENTS = _descriptor.Descriptor(
  name='Requirements',
  full_name='dragonradio.remote.Requirements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_latency_s', full_name='dragonradio.remote.Requirements.max_latency_s', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_throughput_bps', full_name='dragonradio.remote.Requirements.min_throughput_bps', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_packet_drop_rate', full_name='dragonradio.remote.Requirements.max_packet_drop_rate', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_transfer_deadline_s', full_name='dragonradio.remote.Requirements.file_transfer_deadline_s', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_size_bytes', full_name='dragonradio.remote.Requirements.file_size_bytes', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=297,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='dragonradio.remote.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='dragonradio.remote.Status.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='dragonradio.remote.Status.info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=363,
)


_MANDATEDOUTCOMES = _descriptor.Descriptor(
  name='MandatedOutcomes',
  full_name='dragonradio.remote.MandatedOutcomes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='goals', full_name='dragonradio.remote.MandatedOutcomes.goals', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=365,
  serialized_end=424,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='dragonradio.remote.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='radio_command', full_name='dragonradio.remote.Request.radio_command', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_outcomes', full_name='dragonradio.remote.Request.update_outcomes', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='dragonradio.remote.Request.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=427,
  serialized_end=571,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='dragonradio.remote.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='dragonradio.remote.Response.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='dragonradio.remote.Response.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=573,
  serialized_end=640,
)

_GOAL.fields_by_name['requirements'].message_type = _REQUIREMENTS
_STATUS.fields_by_name['state'].enum_type = _STATE
_MANDATEDOUTCOMES.fields_by_name['goals'].message_type = _GOAL
_REQUEST.fields_by_name['radio_command'].enum_type = _RADIOCOMMAND
_REQUEST.fields_by_name['update_outcomes'].message_type = _MANDATEDOUTCOMES
_REQUEST.oneofs_by_name['payload'].fields.append(
  _REQUEST.fields_by_name['radio_command'])
_REQUEST.fields_by_name['radio_command'].containing_oneof = _REQUEST.oneofs_by_name['payload']
_REQUEST.oneofs_by_name['payload'].fields.append(
  _REQUEST.fields_by_name['update_outcomes'])
_REQUEST.fields_by_name['update_outcomes'].containing_oneof = _REQUEST.oneofs_by_name['payload']
_RESPONSE.fields_by_name['status'].message_type = _STATUS
_RESPONSE.oneofs_by_name['payload'].fields.append(
  _RESPONSE.fields_by_name['status'])
_RESPONSE.fields_by_name['status'].containing_oneof = _RESPONSE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['Goal'] = _GOAL
DESCRIPTOR.message_types_by_name['Requirements'] = _REQUIREMENTS
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['MandatedOutcomes'] = _MANDATEDOUTCOMES
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.enum_types_by_name['State'] = _STATE
DESCRIPTOR.enum_types_by_name['RadioCommand'] = _RADIOCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Goal = _reflection.GeneratedProtocolMessageType('Goal', (_message.Message,), dict(
  DESCRIPTOR = _GOAL,
  __module__ = 'dragonradio_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.remote.Goal)
  ))
_sym_db.RegisterMessage(Goal)

Requirements = _reflection.GeneratedProtocolMessageType('Requirements', (_message.Message,), dict(
  DESCRIPTOR = _REQUIREMENTS,
  __module__ = 'dragonradio_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.remote.Requirements)
  ))
_sym_db.RegisterMessage(Requirements)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'dragonradio_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.remote.Status)
  ))
_sym_db.RegisterMessage(Status)

MandatedOutcomes = _reflection.GeneratedProtocolMessageType('MandatedOutcomes', (_message.Message,), dict(
  DESCRIPTOR = _MANDATEDOUTCOMES,
  __module__ = 'dragonradio_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.remote.MandatedOutcomes)
  ))
_sym_db.RegisterMessage(MandatedOutcomes)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'dragonradio_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.remote.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'dragonradio_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.remote.Response)
  ))
_sym_db.RegisterMessage(Response)


# @@protoc_insertion_point(module_scope)
