# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='internal.proto',
  package='dragonradio.internal',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0einternal.proto\x12\x14\x64ragonradio.internal\"1\n\tTimeStamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x05\x12\x13\n\x0bpicoseconds\x18\x02 \x01(\x03\"B\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x11\n\televation\x18\x03 \x01(\x01\"\x86\x01\n\x0cLocationInfo\x12\x10\n\x08radio_id\x18\x01 \x01(\r\x12\x30\n\x08location\x18\x02 \x01(\x0b\x32\x1e.dragonradio.internal.Location\x12\x32\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1f.dragonradio.internal.TimeStamp\"Q\n\x07Message\x12;\n\rlocation_info\x18\x01 \x01(\x0b\x32\".dragonradio.internal.LocationInfoH\x00\x42\t\n\x07payloadb\x06proto3')
)




_TIMESTAMP = _descriptor.Descriptor(
  name='TimeStamp',
  full_name='dragonradio.internal.TimeStamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds', full_name='dragonradio.internal.TimeStamp.seconds', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='picoseconds', full_name='dragonradio.internal.TimeStamp.picoseconds', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=89,
)


_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='dragonradio.internal.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='dragonradio.internal.Location.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='dragonradio.internal.Location.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elevation', full_name='dragonradio.internal.Location.elevation', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=157,
)


_LOCATIONINFO = _descriptor.Descriptor(
  name='LocationInfo',
  full_name='dragonradio.internal.LocationInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='radio_id', full_name='dragonradio.internal.LocationInfo.radio_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='dragonradio.internal.LocationInfo.location', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='dragonradio.internal.LocationInfo.timestamp', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=294,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='dragonradio.internal.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location_info', full_name='dragonradio.internal.Message.location_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='dragonradio.internal.Message.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=296,
  serialized_end=377,
)

_LOCATIONINFO.fields_by_name['location'].message_type = _LOCATION
_LOCATIONINFO.fields_by_name['timestamp'].message_type = _TIMESTAMP
_MESSAGE.fields_by_name['location_info'].message_type = _LOCATIONINFO
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['location_info'])
_MESSAGE.fields_by_name['location_info'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['TimeStamp'] = _TIMESTAMP
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['LocationInfo'] = _LOCATIONINFO
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeStamp = _reflection.GeneratedProtocolMessageType('TimeStamp', (_message.Message,), dict(
  DESCRIPTOR = _TIMESTAMP,
  __module__ = 'internal_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.internal.TimeStamp)
  ))
_sym_db.RegisterMessage(TimeStamp)

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), dict(
  DESCRIPTOR = _LOCATION,
  __module__ = 'internal_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.internal.Location)
  ))
_sym_db.RegisterMessage(Location)

LocationInfo = _reflection.GeneratedProtocolMessageType('LocationInfo', (_message.Message,), dict(
  DESCRIPTOR = _LOCATIONINFO,
  __module__ = 'internal_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.internal.LocationInfo)
  ))
_sym_db.RegisterMessage(LocationInfo)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'internal_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.internal.Message)
  ))
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
