# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: internal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='internal.proto',
  package='dragonradio.internal',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0einternal.proto\x12\x14\x64ragonradio.internal\"1\n\tTimeStamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x05\x12\x13\n\x0bpicoseconds\x18\x02 \x01(\x03\"B\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\x12\x11\n\televation\x18\x03 \x01(\x01\"t\n\x0cLocationInfo\x12\x30\n\x08location\x18\x01 \x01(\x0b\x32\x1e.dragonradio.internal.Location\x12\x32\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1f.dragonradio.internal.TimeStamp\"{\n\x08\x46lowInfo\x12\x10\n\x08\x66low_uid\x18\x01 \x01(\r\x12\x0b\n\x03src\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x65st\x18\x03 \x01(\r\x12\x0e\n\x06window\x18\x04 \x01(\x01\x12\x0f\n\x07latency\x18\x05 \x01(\x01\x12\x12\n\nthroughput\x18\x06 \x01(\x01\x12\r\n\x05\x62ytes\x18\x07 \x01(\x04\"\xe9\x01\n\x06Status\x12\x10\n\x08radio_id\x18\x01 \x01(\r\x12\x32\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1f.dragonradio.internal.TimeStamp\x12/\n\x03loc\x18\x03 \x01(\x0b\x32\".dragonradio.internal.LocationInfo\x12\x34\n\x0csource_flows\x18\x04 \x03(\x0b\x32\x1e.dragonradio.internal.FlowInfo\x12\x32\n\nsink_flows\x18\x05 \x03(\x0b\x32\x1e.dragonradio.internal.FlowInfo\"\x89\x01\n\x08Schedule\x12\x11\n\tfrequency\x18\x01 \x01(\x01\x12\x11\n\tbandwidth\x18\x02 \x01(\x01\x12\x0b\n\x03seq\x18\x03 \x01(\r\x12\x11\n\tnchannels\x18\x04 \x01(\r\x12\x0e\n\x06nslots\x18\x05 \x01(\r\x12\x11\n\x05nodes\x18\x06 \x03(\rB\x02\x10\x01\x12\x14\n\x08schedule\x18\x07 \x03(\rB\x02\x10\x01\"x\n\x07Message\x12.\n\x06status\x18\x01 \x01(\x0b\x32\x1c.dragonradio.internal.StatusH\x00\x12\x32\n\x08schedule\x18\x02 \x01(\x0b\x32\x1e.dragonradio.internal.ScheduleH\x00\x42\t\n\x07payloadb\x06proto3')
)




_TIMESTAMP = _descriptor.Descriptor(
  name='TimeStamp',
  full_name='dragonradio.internal.TimeStamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds', full_name='dragonradio.internal.TimeStamp.seconds', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='picoseconds', full_name='dragonradio.internal.TimeStamp.picoseconds', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=89,
)


_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='dragonradio.internal.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='dragonradio.internal.Location.latitude', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='dragonradio.internal.Location.longitude', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='elevation', full_name='dragonradio.internal.Location.elevation', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=157,
)


_LOCATIONINFO = _descriptor.Descriptor(
  name='LocationInfo',
  full_name='dragonradio.internal.LocationInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='dragonradio.internal.LocationInfo.location', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='dragonradio.internal.LocationInfo.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=275,
)


_FLOWINFO = _descriptor.Descriptor(
  name='FlowInfo',
  full_name='dragonradio.internal.FlowInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flow_uid', full_name='dragonradio.internal.FlowInfo.flow_uid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='src', full_name='dragonradio.internal.FlowInfo.src', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dest', full_name='dragonradio.internal.FlowInfo.dest', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='window', full_name='dragonradio.internal.FlowInfo.window', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latency', full_name='dragonradio.internal.FlowInfo.latency', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='throughput', full_name='dragonradio.internal.FlowInfo.throughput', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bytes', full_name='dragonradio.internal.FlowInfo.bytes', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=400,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='dragonradio.internal.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='radio_id', full_name='dragonradio.internal.Status.radio_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='dragonradio.internal.Status.timestamp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loc', full_name='dragonradio.internal.Status.loc', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_flows', full_name='dragonradio.internal.Status.source_flows', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sink_flows', full_name='dragonradio.internal.Status.sink_flows', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=636,
)


_SCHEDULE = _descriptor.Descriptor(
  name='Schedule',
  full_name='dragonradio.internal.Schedule',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frequency', full_name='dragonradio.internal.Schedule.frequency', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bandwidth', full_name='dragonradio.internal.Schedule.bandwidth', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seq', full_name='dragonradio.internal.Schedule.seq', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nchannels', full_name='dragonradio.internal.Schedule.nchannels', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nslots', full_name='dragonradio.internal.Schedule.nslots', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='dragonradio.internal.Schedule.nodes', index=5,
      number=6, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schedule', full_name='dragonradio.internal.Schedule.schedule', index=6,
      number=7, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=_b('\020\001'), file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=639,
  serialized_end=776,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='dragonradio.internal.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='dragonradio.internal.Message.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='schedule', full_name='dragonradio.internal.Message.schedule', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='dragonradio.internal.Message.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=778,
  serialized_end=898,
)

_LOCATIONINFO.fields_by_name['location'].message_type = _LOCATION
_LOCATIONINFO.fields_by_name['timestamp'].message_type = _TIMESTAMP
_STATUS.fields_by_name['timestamp'].message_type = _TIMESTAMP
_STATUS.fields_by_name['loc'].message_type = _LOCATIONINFO
_STATUS.fields_by_name['source_flows'].message_type = _FLOWINFO
_STATUS.fields_by_name['sink_flows'].message_type = _FLOWINFO
_MESSAGE.fields_by_name['status'].message_type = _STATUS
_MESSAGE.fields_by_name['schedule'].message_type = _SCHEDULE
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['status'])
_MESSAGE.fields_by_name['status'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
_MESSAGE.oneofs_by_name['payload'].fields.append(
  _MESSAGE.fields_by_name['schedule'])
_MESSAGE.fields_by_name['schedule'].containing_oneof = _MESSAGE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['TimeStamp'] = _TIMESTAMP
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['LocationInfo'] = _LOCATIONINFO
DESCRIPTOR.message_types_by_name['FlowInfo'] = _FLOWINFO
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['Schedule'] = _SCHEDULE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeStamp = _reflection.GeneratedProtocolMessageType('TimeStamp', (_message.Message,), dict(
  DESCRIPTOR = _TIMESTAMP,
  __module__ = 'internal_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.internal.TimeStamp)
  ))
_sym_db.RegisterMessage(TimeStamp)

Location = _reflection.GeneratedProtocolMessageType('Location', (_message.Message,), dict(
  DESCRIPTOR = _LOCATION,
  __module__ = 'internal_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.internal.Location)
  ))
_sym_db.RegisterMessage(Location)

LocationInfo = _reflection.GeneratedProtocolMessageType('LocationInfo', (_message.Message,), dict(
  DESCRIPTOR = _LOCATIONINFO,
  __module__ = 'internal_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.internal.LocationInfo)
  ))
_sym_db.RegisterMessage(LocationInfo)

FlowInfo = _reflection.GeneratedProtocolMessageType('FlowInfo', (_message.Message,), dict(
  DESCRIPTOR = _FLOWINFO,
  __module__ = 'internal_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.internal.FlowInfo)
  ))
_sym_db.RegisterMessage(FlowInfo)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'internal_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.internal.Status)
  ))
_sym_db.RegisterMessage(Status)

Schedule = _reflection.GeneratedProtocolMessageType('Schedule', (_message.Message,), dict(
  DESCRIPTOR = _SCHEDULE,
  __module__ = 'internal_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.internal.Schedule)
  ))
_sym_db.RegisterMessage(Schedule)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'internal_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.internal.Message)
  ))
_sym_db.RegisterMessage(Message)


_SCHEDULE.fields_by_name['nodes']._options = None
_SCHEDULE.fields_by_name['schedule']._options = None
# @@protoc_insertion_point(module_scope)
