# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='remote.proto',
  package='dragonradio.remote',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cremote.proto\x12\x12\x64ragonradio.remote\"@\n\x06Status\x12(\n\x05state\x18\x01 \x01(\x0e\x32\x19.dragonradio.remote.State\x12\x0c\n\x04info\x18\x02 \x01(\t\"!\n\x10MandatedOutcomes\x12\r\n\x05goals\x18\x01 \x01(\t\"\"\n\x0b\x45nvironment\x12\x13\n\x0b\x65nvironment\x18\x01 \x01(\t\"\xeb\x01\n\x07Request\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x39\n\rradio_command\x18\x02 \x01(\x0e\x32 .dragonradio.remote.RadioCommandH\x00\x12H\n\x18update_mandated_outcomes\x18\x03 \x01(\x0b\x32$.dragonradio.remote.MandatedOutcomesH\x00\x12=\n\x12update_environment\x18\x04 \x01(\x0b\x32\x1f.dragonradio.remote.EnvironmentH\x00\x42\t\n\x07payload\"C\n\x08Response\x12,\n\x06status\x18\x01 \x01(\x0b\x32\x1a.dragonradio.remote.StatusH\x00\x42\t\n\x07payload*[\n\x05State\x12\x07\n\x03OFF\x10\x00\x12\x0b\n\x07\x42OOTING\x10\x01\x12\t\n\x05READY\x10\x02\x12\n\n\x06\x41\x43TIVE\x10\x03\x12\x0c\n\x08STOPPING\x10\x04\x12\x0c\n\x08\x46INISHED\x10\x05\x12\t\n\x05\x45RROR\x10\x06*/\n\x0cRadioCommand\x12\t\n\x05START\x10\x00\x12\x08\n\x04STOP\x10\x01\x12\n\n\x06STATUS\x10\x02\x62\x06proto3')
)

_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='dragonradio.remote.State',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFF', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOOTING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='READY', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACTIVE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOPPING', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FINISHED', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=480,
  serialized_end=571,
)
_sym_db.RegisterEnumDescriptor(_STATE)

State = enum_type_wrapper.EnumTypeWrapper(_STATE)
_RADIOCOMMAND = _descriptor.EnumDescriptor(
  name='RadioCommand',
  full_name='dragonradio.remote.RadioCommand',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=573,
  serialized_end=620,
)
_sym_db.RegisterEnumDescriptor(_RADIOCOMMAND)

RadioCommand = enum_type_wrapper.EnumTypeWrapper(_RADIOCOMMAND)
OFF = 0
BOOTING = 1
READY = 2
ACTIVE = 3
STOPPING = 4
FINISHED = 5
ERROR = 6
START = 0
STOP = 1
STATUS = 2



_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='dragonradio.remote.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='dragonradio.remote.Status.state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='dragonradio.remote.Status.info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=100,
)


_MANDATEDOUTCOMES = _descriptor.Descriptor(
  name='MandatedOutcomes',
  full_name='dragonradio.remote.MandatedOutcomes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='goals', full_name='dragonradio.remote.MandatedOutcomes.goals', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=135,
)


_ENVIRONMENT = _descriptor.Descriptor(
  name='Environment',
  full_name='dragonradio.remote.Environment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='environment', full_name='dragonradio.remote.Environment.environment', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=171,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='dragonradio.remote.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='dragonradio.remote.Request.timestamp', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='radio_command', full_name='dragonradio.remote.Request.radio_command', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_mandated_outcomes', full_name='dragonradio.remote.Request.update_mandated_outcomes', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_environment', full_name='dragonradio.remote.Request.update_environment', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='dragonradio.remote.Request.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=174,
  serialized_end=409,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='dragonradio.remote.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='dragonradio.remote.Response.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='dragonradio.remote.Response.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=411,
  serialized_end=478,
)

_STATUS.fields_by_name['state'].enum_type = _STATE
_REQUEST.fields_by_name['radio_command'].enum_type = _RADIOCOMMAND
_REQUEST.fields_by_name['update_mandated_outcomes'].message_type = _MANDATEDOUTCOMES
_REQUEST.fields_by_name['update_environment'].message_type = _ENVIRONMENT
_REQUEST.oneofs_by_name['payload'].fields.append(
  _REQUEST.fields_by_name['radio_command'])
_REQUEST.fields_by_name['radio_command'].containing_oneof = _REQUEST.oneofs_by_name['payload']
_REQUEST.oneofs_by_name['payload'].fields.append(
  _REQUEST.fields_by_name['update_mandated_outcomes'])
_REQUEST.fields_by_name['update_mandated_outcomes'].containing_oneof = _REQUEST.oneofs_by_name['payload']
_REQUEST.oneofs_by_name['payload'].fields.append(
  _REQUEST.fields_by_name['update_environment'])
_REQUEST.fields_by_name['update_environment'].containing_oneof = _REQUEST.oneofs_by_name['payload']
_RESPONSE.fields_by_name['status'].message_type = _STATUS
_RESPONSE.oneofs_by_name['payload'].fields.append(
  _RESPONSE.fields_by_name['status'])
_RESPONSE.fields_by_name['status'].containing_oneof = _RESPONSE.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['MandatedOutcomes'] = _MANDATEDOUTCOMES
DESCRIPTOR.message_types_by_name['Environment'] = _ENVIRONMENT
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.enum_types_by_name['State'] = _STATE
DESCRIPTOR.enum_types_by_name['RadioCommand'] = _RADIOCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'remote_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.remote.Status)
  ))
_sym_db.RegisterMessage(Status)

MandatedOutcomes = _reflection.GeneratedProtocolMessageType('MandatedOutcomes', (_message.Message,), dict(
  DESCRIPTOR = _MANDATEDOUTCOMES,
  __module__ = 'remote_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.remote.MandatedOutcomes)
  ))
_sym_db.RegisterMessage(MandatedOutcomes)

Environment = _reflection.GeneratedProtocolMessageType('Environment', (_message.Message,), dict(
  DESCRIPTOR = _ENVIRONMENT,
  __module__ = 'remote_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.remote.Environment)
  ))
_sym_db.RegisterMessage(Environment)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'remote_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.remote.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'remote_pb2'
  # @@protoc_insertion_point(class_scope:dragonradio.remote.Response)
  ))
_sym_db.RegisterMessage(Response)


# @@protoc_insertion_point(module_scope)
