- name: Install packages required for building DragonRadio
  apt:
    state: present
    pkg:
      - autoconf
      - automake
      - build-essential
      - cmake
      # For UHD
      - libboost-dev
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-regex-dev
      - libboost-system-dev
      - libboost-serialization-dev
      - libboost-test-dev
      - libboost-thread-dev
      # For liquid-dsp
      - libncurses5-dev
      - libfftw3-dev
      # For HDF5
      - libhdf5-dev
      # For FLAC
      - libflac8
      - libflac-dev
      - libflac++-dev
      # For firpm
      - libeigen3-dev
      # For python
      - python3
      - python3-dev
      - python3-distutils
      - python3-pip
      - python3-virtualenv
      - virtualenv
      # For gpsd
      - scons
      # For dragonradio tun/tap
      - net-tools

- name: Install packages required for USB-based USRP support
  apt:
    state: present
    pkg:
      - libusb-1.0-0-dev
  when: usb | bool

- name: Remove unneeded packages
  apt:
    state: absent
    pkg:
      - snapd
      - squashfs-tools

- name: Remove unneeded directories
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - /var/snap
  ignore_errors: yes
